---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

run:
  path: source-repo/tasks/cf-push/task.sh

params:
    CF_USERNAME:
    CF_TARGET:
    CF_PASSWORD:
    CF_ORG:
    CF_SPACE: