---
resources:
- name: source-repo
  type: git
  source:
    uri: https://github.com/patrick-huber-pivotal/delltraining-dotnet-core
    username: ((git_username))
    password: ((git_password))
jobs:
- name: push
  public: true
  plan:
  - get: source-repo
  - task: push
    file: source-repo/ci/tasks/cf-push/task.yml
    params:
      CF_USERNAME: ((cf_username))
      CF_TARGET: ((cf_target))
      CF_PASSWORD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_space))